from core import mod_utils as utils
import torch
import torch.nn as nn
from torch.optim import Adam
from torch.autograd import Variable
import torch.nn.functional as F
from torch.nn import Parameter
import numpy as np
from torch.distributions import Categorical
GPU = True
device_idx = 0



if GPU:
    device = torch.device("cuda:" + str(device_idx) if torch.cuda.is_available() else "cpu")
else:
    device = torch.device("cpu")
print(device)




class Flatten(nn.Module):
    def forward(self, x):
        # print(x.size())
        out = x.view(x.size(0), -1)
        # print(out.size())
        # input()
        return out

def soft_update(target, source, tau):
    for target_param, param in zip(target.parameters(), source.parameters()):
        target_param.data.copy_(target_param.data * (1.0 - tau) + param.data * tau)

def hard_update(target, source):
    for target_param, param in zip(target.parameters(), source.parameters()):
        target_param.data.copy_(param.data)

#Use the actor to predict the action, given the state
class Actor(nn.Module):

    def __init__(self, args, init=False):
        super(Actor, self).__init__()
        self.args = args
        self.saved_log_probs =[]

        num_outputs = self.args.action_dim
        num_channel = self.args.state_dim

        self.cnn = nn.Sequential(
             nn.Conv2d(num_channel, 32, 8, stride=3), nn.ReLU(),
             nn.Conv2d(32, 64, 4, stride=2),
             nn.Conv2d(64, 16, 4, stride=2), nn.ReLU(),
             nn.Conv2d(16, 8, 3, stride=1), Flatten(),
             nn.Linear(8 * 3 * 3, num_outputs), nn.ReLU())
        self.to(device = device)
    def forward(self, state):

        in_size = state.size()#batch, H,W,channel
        state = state.permute(0,3,1,2) #batch, channel, H, W

        out = self.cnn(state)
        #Output the probability disctribution of  the action
        probability = F.softmax(out, dim = -1) #[-1,1] ouput the action

        out = Categorical(probability)
        action = out.sample()#sample action
        #self.saved_log_probs.append(out.log_prob(action))
        #print("---sample action:" ,action, action.item())
        #input()
        return action

#Given the action generated by the actor and the state, predict the q value
class Critic(nn.Module):

    def __init__(self, args):
        super(Critic, self).__init__()
        self.args = args

        l1 = 100; l2 = 200; l3 = l2
        self.cnn = nn.Sequential(
             nn.Conv2d(self.args.state_dim, 32, 8, stride=3), nn.ReLU(),
             nn.Conv2d(32, 64, 4, stride=2),
             nn.Conv2d(64, 16, 4, stride=2), nn.ReLU(),
             nn.Conv2d(16, 8, 3, stride=1), Flatten(),
             nn.Linear(8 * 3 * 3, l1), nn.ReLU())
        # Construct input interface (Hidden Layer 1)
        self.w_state_l1 = nn.Linear(args.state_dim, l1)
        self.w_action_l1 = nn.Linear(1, l1)#action is one a single tensor
        self.w_action = nn.Linear(1,l1)
        #Hidden Layer 2
        self.w_l2 = nn.Linear(2*l1, l2)
        if self.args.use_ln: self.lnorm2 = LayerNorm(l2)

        #Out
        self.w_out = nn.Linear(l3, 1)
        self.w_out.weight.data.mul_(0.1)
        self.w_out.bias.data.mul_(0.1)

        self.to(device=device)

    def forward(self, state, action):
        #Hidden Layer 1 (Input Interface)
        state = state.permute(0,3,1,2) #batch, channel, H, W
        out_state = F.elu(self.cnn(state))
        #print(" out state size: ", out_state.size())
        action = action.view(action.size(0),1)#batch_size, 1
        out_action = F.elu(self.w_action(action.float()))
        
        out = torch.cat((out_state, out_action), 1)

        # Hidden Layer 2
        out = self.w_l2(out)
        if self.args.use_ln: out = self.lnorm2(out)
        out = F.elu(out)

        # Output interface
        out = self.w_out(out) #output the predicted Q value for the state and the action(actor)

        return out




class DDPG(object):
    def __init__(self, args):

        self.args = args

        self.actor = Actor(args, init=True)
        self.actor_target = Actor(args, init=True)
        self.actor_optim = Adam(self.actor.parameters(), lr=0.5e-4)

        self.critic = Critic(args)
        self.critic_target = Critic(args)
        self.critic_optim = Adam(self.critic.parameters(), lr=0.5e-3)

        self.gamma = args.gamma; self.tau = self.args.tau
        self.loss = nn.MSELoss()

        hard_update(self.actor_target, self.actor)  # Make sure target is with the same weight
        hard_update(self.critic_target, self.critic)

    def update_parameters(self, batch):
        #print("------------------------------------batch---------")
        #print("state size: ", len(batch.state))

        #print("next_state size: ", len(batch.next_state))


        state_batch = torch.cat(batch.state)
        next_state_batch = torch.cat(batch.next_state)
        action_batch = torch.cat(batch.action)
        reward_batch = torch.cat(batch.reward)
        if self.args.use_done_mask: done_batch = torch.cat(batch.done)
        state_batch.requires_grad=True; next_state_batch.requires_grad=False; action_batch.requires_grad_=True
        
        #Load everything to GPU if not already
        if self.args.is_memory_cuda and not self.args.is_cuda:
            self.actor.to(device= device)
            self.actor_target.to(device= device)
            self.critic_target.to(device= device)
            self.critic.to(device=device)

            self.actor.train()
            self.actor_target.train()
            self.critic_target.train()
            self.critic.train()
            state_batch = state_batch.to(device=device); next_state_batch = next_state_batch.to(device=device); action_batch = action_batch.to(device=device); reward_batch = reward_batch.to(device=device)
            if self.args.use_done_mask: done_batch = done_batch.to(device=device)



        # print("--------after cat state_batch: ",state_batch.size() )
        # print("--------after cat next_state_batch: ",next_state_batch.size() )
        # print("--------after cat action_batch: ",action_batch.size() )
        # print("--------after cat reward_batch: ",reward_batch.size() )
        #Critic Update
        # print("---update critic: ", next_state_batch.size())
        # input()
        next_action_batch = self.actor_target.forward(next_state_batch)
        next_action_batch.to(device=device)
        #print("----next_action for critic: ", next_action_batch.size())
        #input()
        next_q = self.critic_target.forward(next_state_batch, next_action_batch)
        if self.args.use_done_mask: next_q = next_q * ( 1 - done_batch.float()) #Done mask
        target_q = reward_batch + (self.gamma * next_q)

        self.critic_optim.zero_grad()
        current_q = self.critic.forward((state_batch), (action_batch))
        dt = self.loss(current_q, target_q)
        dt.backward()
        nn.utils.clip_grad_norm(self.critic.parameters(), 10)
        self.critic_optim.step()

        #Actor Update
        self.actor_optim.zero_grad()
        policy_loss = -self.critic.forward((state_batch),self.actor.forward((state_batch)))
        policy_loss = policy_loss.mean()
        policy_loss.backward()
        self.actor_optim.step()

        soft_update(self.actor_target, self.actor, self.tau)
        soft_update(self.critic_target, self.critic, self.tau)

        #Nets back to CPU if using memory_cuda
        if self.args.is_memory_cuda and not self.args.is_cuda: self.actor.cpu(); self.actor_target.cpu(); self.critic_target.cpu(); self.critic.cpu()


def fanin_init(size, fanin=None):
    v = 0.008
    return torch.Tensor(size).uniform_(-v, v)

def actfn_none(inp): return inp

class LayerNorm(nn.Module):

    def __init__(self, features, eps=1e-6):
        super().__init__()
        self.gamma = nn.Parameter(torch.ones(features))
        self.beta = nn.Parameter(torch.zeros(features))
        self.eps = eps

    def forward(self, x):
        mean = x.mean(-1, keepdim=True)
        std = x.std(-1, keepdim=True)
        return self.gamma * (x - mean) / (std + self.eps) + self.beta

class OUNoise:

    def __init__(self, action_dimension, scale=0.3, mu=0, theta=0.15, sigma=0.2):
        self.action_dimension = action_dimension
        self.scale = scale
        self.mu = mu
        self.theta = theta
        self.sigma = sigma
        self.state = np.ones(self.action_dimension) * self.mu
        self.reset()

    def reset(self):
        self.state = np.ones(self.action_dimension) * self.mu

    def noise(self):
        x = self.state
        dx = self.theta * (self.mu - x) + self.sigma * np.random.randn(len(x))
        self.state = x + dx
        return self.state * self.scale
